services:
  web:
    env_file:
      - .env
    build: .
    ports:
      - "80:8080"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    volumes:
      - /data/github/classics/db
    environment:
      POSTGRES_DB: classics_database
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "9999:9999"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U postgres"]
      interval: 1s