services:
  web:
    env_file:
      - .env
    build: .
    ports:
      - "8080:8080"
  db:
    image: postgres
    volumes:
      - /classics/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: classics_database
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s