services:
  web:
    env_file:
      - .env
    build: .
    ports:
      - "25611:31234"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    volumes:
      - ./classics/db:/var/lib/classics/db
