services:
  web:
    env_file:
      - .env
    image: blackhig/yc2-classics
    ports:
      - "80:8080"
    restart: always
    volumes:
      - ./classics:/var/lib/classics/
      - ./logs:/app/logs
