name: Gradle Publish Docker Image

on:
  push:
    branches:
      - master

jobs:
  docker-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: temurin

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Publish Docker Image
      run: ./gradlew publishImage
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}